import json
import os
import re

def resolve_token(value, all_tokens, mode='light'):
    """Resolves token references like {primitive.color.blue.8} or {semantic.color.bg.primary}"""
    if not isinstance(value, str):
        return value
    
    match = re.match(r'^\{(.*)\}$', value)
    if not match:
        return value
    
    path = match.group(1).split('.')
    ref = all_tokens
    for part in path:
        if isinstance(ref, dict):
            ref = ref.get(part, {})
        else:
            return value # Fallback if path is invalid
    
    if isinstance(ref, dict):
        if mode in ref:
            return resolve_token(ref[mode], all_tokens, mode)
        if 'value' in ref:
            return resolve_token(ref['value'], all_tokens, mode)
    return ref

def generate_css(tokens):
    css_lines = [
        "/* [GENERATED] This file is automatically generated from tokens.json. */",
        "/* DO NOT EDIT MANUALLY. */",
        ":root {"
    ]
    dark_mode_lines = ["\nhtml.dark-mode {"]
    
    # 1-3: Primitives (usually theme-independent or base for semantic)
    # Primitives
    for section in ['primitive']:
        data = tokens.get(section, {})
        for category, items in data.items():
            css_lines.append(f"\n    /* {section.capitalize()} {category.capitalize()} */")
            prefix = ""
            if category == 'spacing': prefix = "spacing-"
            elif category == 'radius': prefix = "radius-"
            elif category == 'border-width': prefix = "border-width-"
            elif category == 'typography': prefix = "" # Typography handles its own nesting
            
            for group, val in items.items():
                if isinstance(val, dict) and 'value' in val:
                    css_lines.append(f"    --{prefix}{group}: {val['value']};")
                elif isinstance(val, dict):
                    # Recursive for typography or nested primitives
                    def process_primitive(path, data):
                        for k, v in data.items():
                            current_path = f"{path}-{k}" if path else k
                            if isinstance(v, dict) and 'value' in v:
                                css_lines.append(f"    --{prefix}{current_path}: {v['value']};")
                            elif isinstance(v, dict):
                                process_primitive(current_path, v)
                    
                    process_primitive(group, val)

    # 4. Generate Semantic Categories
    semantic = tokens.get('semantic', {})
    for category_name, category_data in semantic.items():
        css_lines.append(f"\n    /* Semantic {category_name.capitalize()} */")
        dark_mode_lines.append(f"    /* Semantic {category_name.capitalize()} Overrides */")
        
        for group, roles in category_data.items():
            if not isinstance(roles, dict): continue
            
            # Helper to process a leaf token
            def handle_leaf(var_name, token_data):
                # Light/Default
                if 'light' in token_data:
                    val = resolve_token(token_data['light'], tokens, 'light')
                    css_lines.append(f"    {var_name}: {val};")
                elif 'value' in token_data:
                    val = resolve_token(token_data['value'], tokens, 'light')
                    css_lines.append(f"    {var_name}: {val};")
                
                # Dark Override
                if 'dark' in token_data:
                    val = resolve_token(token_data['dark'], tokens, 'dark')
                    dark_mode_lines.append(f"    {var_name}: {val};")

            if 'value' in roles or 'light' in roles or 'dark' in roles:
                # Direct role (e.g. semantic.shadow.small)
                name = f"--{category_name}-{group}"
                handle_leaf(name, roles)
            else:
                # Nested roles (e.g. semantic.color.bg.primary)
                for role, data in roles.items():
                    if not isinstance(data, dict): continue
                    
                    if 'value' in data or 'light' in data or 'dark' in data:
                        name = f"--{group}-{role}" if category_name == 'color' else f"--{category_name}-{group}-{role}"
                        handle_leaf(name, data)
                    else:
                        # Deeper nesting (e.g. state.hover.primary)
                        for subrole, subdata in data.items():
                            if not isinstance(subdata, dict): continue
                            name = f"--{group}-{role}-{subrole}" if category_name == 'color' else f"--{category_name}-{group}-{role}-{subrole}"
                            handle_leaf(name, subdata)

    css_lines.append("}")
    dark_mode_lines.append("}")
    
    return "\n".join(css_lines) + "\n" + "\n".join(dark_mode_lines)

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    tokens_path = os.path.join(base_dir, 'tokens.json')
    output_path = os.path.join(base_dir, 'design_system.css')
    
    if not os.path.exists(tokens_path):
        print(f"Error: {tokens_path} not found")
        return

    with open(tokens_path, 'r') as f:
        tokens = json.load(f)
    
    css_content = generate_css(tokens)
    
    with open(output_path, 'w') as f:
        f.write(css_content)
    
    print(f"Successfully generated {output_path}")

if __name__ == "__main__":
    main()
